#theme = "acme"
theme = "gruvbox"

[editor]
  auto-save  = true
  rulers = [80, 100, 120]
  shell      = ["fish"]
  text-width = 120
  true-color = true

  [editor.cursor-shape]
    insert = "bar"
    normal = "block"
    select = "underline"

  [editor.file-picker]
    hidden = false

  [editor.whitespace.render]
    nbsp    = "none"
    newline = "none"
    nnbsp   = "none"
    space   = "none"
    tab     = "all"
    tabpad  = "none"

  [editor.whitespace.characters]
    nbsp    = "⍽"
    newline = "⏎"
    nnbsp   = "␣"
    space   = "·"
    tab     = "→"
    tabpad  = "·"

  [editor.indent-guides]
    character   = "┊"
    render      = true
    skip-levels = 1

[keys]
  [keys.normal]
    X = ["extend_line_up", "extend_to_line_bounds"]

  # Emacs mode
  [keys.insert]
    C-a = "goto_line_start"
    C-b = "move_char_left"
    C-e = "goto_line_end_newline"
    C-f = "move_char_right"
    C-h = "delete_char_backward"
    C-k = "kill_to_line_end"
    C-n = "move_line_down"
    C-p = "move_line_up"
