live_config_reload = true


[shell]
# program = "/usr/bin/fish"
# args = ["--command=tmux]

program = "/usr/bin/nu"
args = ["-e tmux"]


[window]
dimensions.columns = 80
dimensions.lines = 55
dynamic_padding = true
opacity = 1.0
padding.x = 3
padding.y = 3


[scrolling]
history = 100000
multiplier = 3


[colors]
cursor.text = "#ffffff"
cursor.cursor = "#ff0000"


[cursor]
style.shape = "Underline"
style.blinking = "On"
thickness = 0.5


[font]
normal.family = "ZedMono Nerd Font"
normal.style = "Regular"
size = 12


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true
