[colors]
  cursor.cursor = "#ff0000"
  cursor.text   = "#ffffff"


[cursor]
  style.blinking = "On"
  style.shape    = "Beam"
  thickness      = 0.2


[font]
  normal.family = "BlexMono Nerd Font"
  normal.style  = "Regular"
  size          = 16

  [font.offset]
    x = 1
    y = 1


[general]
  import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml.toml",
  ]
  live_config_reload = true


[selection]
  save_to_clipboard     = true
  semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[scrolling]
  history    = 100000
  multiplier = 3


[terminal]
  osc52 = "OnlyCopy"
  shell = {program = "/bin/zsh"}


[window]
  dimensions.columns = 120
  dimensions.lines   = 55
  dynamic_padding    = true
  opacity            = 1.0
  option_as_alt      = 'Both'
  padding.x          = 3
  padding.y          = 3
