[general]
  live_config_reload = true


[terminal]
  osc52 = "OnlyCopy"
  # shell = { program = "Ubuntu" } # for WSL2

[window]
  dimensions.columns = 80
  dimensions.lines   = 55
  dynamic_padding    = true
  opacity            = 1.0
  padding.x          = 3
  padding.y          = 3


[scrolling]
  history    = 100000
  multiplier = 3


[colors]
  cursor.cursor = "#ff0000"
  cursor.text   = "#ffffff"


[cursor]
  style.blinking = "On"
  style.shape    = "Beam"
  thickness      = 0.2


[font]
  normal.family = "CaskaydiaMono Nerd Font"
  normal.style  = "Regular"
  size          = 11


  [font.offset]
    x = 1
    y = 1


[selection]
  save_to_clipboard     = true
  semantic_escape_chars = ",│`|:\"' ()[]{}<>"
