[general]
live_config_reload = true


#[shell]
# program = "/usr/bin/fish"
# args = ["--command=tmux]
## program = "/usr/bin/nu"
## args = ["-e tmux"]


[window]
dimensions.columns = 80
dimensions.lines = 55
dynamic_padding = true
opacity = 1.0
padding.x = 3
padding.y = 3


[scrolling]
history = 100000
multiplier = 3


[colors]
cursor.text = "#ffffff"
cursor.cursor = "#ff0000"


[cursor]
style.shape = "Beam"
style.blinking = "On"
thickness = 0.2


[font]
normal.family = "CaskaydiaMono Nerd Font"
normal.style = "light"
size = 14


[font.offset]
x = 2
y = 2


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true
