[target.x86_64-apple-darwin]
  rustflags = [
    "-C",
    "-C",
    "link-arg=-undefined",
    "link-arg=dynamic_lookup",
  ]

[target.aarch64-apple-darwin]
  rustflags = [
    "-C",
    "-C",
    "link-arg=-undefined",
    "link-arg=dynamic_lookup",
  ]
