[manager]
  ratio       = [1, 2, 5]
  show_hidden = true

[preview]
  tab_size = 2

[opener]
  edit = [
    { run = 'hx "$@"', block = true },
    #{run = 'emacsclient -c "$@"', block = true},
    #{ run = 'nvim "$@"', block = true },
  ]
