[manager]
  append_keymap = [
    {on = ["<A-v>"], run = "arrow -5", desc = "Move cursor up 5 lines"},
    {on = ["<C-n>"], run = "arrow  1", desc = "Move cursor down"},
    {on = ["<C-p>"], run = "arrow -1", desc = "Move cursor up"},
    {on = ["<C-v>"], run = "arrow  5", desc = "Move cursor down 5 lines"},
    {on = ["e"], run = "open", desc = "Open the selected files"},
  ]
