[manager]
  ratio = [1, 2, 5]

[preview]
  tab_size = 2

[opener]
  edit = [
    {run = 'emacsclient -c "$@"', block = true},
    #{ run = 'emacs "$@"', block = true },
    #{ run = 'nvim "$@"', block = true },
    #{ run = 'hx "$@"', block = true },
  ]
